# -*- coding: utf-8 -*-
"""Agente RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bEw4yZRTQqq3d9nVuINgctWrb6huyVd1
"""

import os

from langchain_community.document_loaders import PyPDFLoader

from langchain_text_splitters import RecursiveCharacterTextSplitter

from langchain_community.vectorstores import FAISS

from langchain_community.embeddings import HuggingFaceEmbeddings

from langchain_google_genai import ChatGoogleGenerativeAI

import gradio as gr

print("Librerías cargadas")

RUTA_DOCUMENTOS = "documentos"

CHUNK_SIZE = 1000
CHUNK_OVERLAP = 200

MODELO_EMBEDDINGS = "sentence-transformers/all-MiniLM-L6-v2"

MODELO_GEMINI = "gemini-3.1-flash-lite"

TOP_K = 5

print("Configuración lista")

documentos = []

if not os.path.exists(RUTA_DOCUMENTOS):
    raise Exception(f"No existe la carpeta {RUTA_DOCUMENTOS}")

print("Archivos encontrados:\n")

for archivo in os.listdir(RUTA_DOCUMENTOS):

    if archivo.lower().endswith(".pdf"):

        print("•", archivo)

        loader = PyPDFLoader(
            os.path.join(RUTA_DOCUMENTOS, archivo)
        )

        documentos.extend(loader.load())

print()

print(" Total de páginas:", len(documentos))

splitter = RecursiveCharacterTextSplitter(
    chunk_size=CHUNK_SIZE,
    chunk_overlap=CHUNK_OVERLAP
)

chunks = splitter.split_documents(documentos)

print("Fragmentos creados:", len(chunks))

embeddings = HuggingFaceEmbeddings(
    model_name=MODELO_EMBEDDINGS
)

print("Embeddings cargados")

vectorstore = FAISS.from_documents(
    documents=chunks,
    embedding=embeddings
)

print("Base vectorial creada")

api_key = os.getenv("GEMINI_API_KEY")

if api_key is None:
    raise ValueError("No se encontró la variable GEMINI_API_KEY")

os.environ["GOOGLE_API_KEY"] = api_key

llm = ChatGoogleGenerativeAI(
    model=MODELO_GEMINI,
    temperature=0
)

print(" Gemini configurado")

def limpiar_respuesta(respuesta):

    contenido = respuesta.content

    if isinstance(contenido, list):

        texto = ""

        for bloque in contenido:

            if isinstance(bloque, dict):

                if bloque.get("type") == "text":

                    texto += bloque.get("text", "")

        return texto.strip()

    if isinstance(contenido, str):

        return contenido.strip()

    return str(contenido)

def responder_usuario(pregunta):

    documentos = vectorstore.similarity_search(
        pregunta,
        k=TOP_K
    )

    contexto = "\n\n".join(
        doc.page_content
        for doc in documentos
    )

    prompt = f"""
Eres el asistente virtual de atención al cliente de BimBam Buy.

Tu objetivo es ayudar al usuario respondiendo preguntas sobre la información disponible en los documentos.

Debes responder únicamente utilizando la información del contexto.

Reglas:

- Responde de forma clara y cordial.
- Si la información es parcial, explícalo.
- No inventes datos.
- Si existe información relacionada, úsala.
- Si realmente no existe información suficiente, indícalo.

CONTEXTO

{contexto}

PREGUNTA

{pregunta}

RESPUESTA
"""

    respuesta = llm.invoke(prompt)

    return limpiar_respuesta(respuesta)

respuesta = responder_usuario(
    "¿Cómo puedo acceder al envío gratis?"
)

print(respuesta)

interfaz = gr.Interface(

    fn=responder_usuario,

    inputs=gr.Textbox(
        lines=2,
        placeholder="Escribe tu consulta..."
    ),

    outputs=gr.Textbox(
        label="Respuesta"
    ),

    title="🛒 Asistente Virtual BimBam Buy",

    description="""
Consulta información sobre:

• Pagos
• Envíos
• Reembolsos
• Devoluciones
• Programa de afiliados
• Promociones
"""
)

print("✅ Interfaz creada")

if __name__ == "__main__":

    interfaz.launch(
        server_name="0.0.0.0",
        server_port=7860,
        share=False
    )
